Lint/HandleExceptions:
  Exclude:
    - "spec/**/*"

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - lib/tasks/**/*
    - "**/spec/**/*"
  ExcludedMethods:
    - namespace

Style/ConditionalAssignment:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - lib/expansion_rules.rb
