default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_API_KEY'] %>"
  name: "Publishing API"
  active: <%= ENV['APPSIGNAL_API_KEY'] ? true : false %>

development:
  <<: *defaults

production:
  <<: *defaults
