development:
  adapter: postgresql
  encoding: unicode
  database: publishing_api_development
  pool: 5
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: publishing_api_test
  pool: 5
  template: template0
