defaults: &defaults
  hosts: [localhost]
  port: 5672
  vhost: /
  user: publishing_api
  pass: publishing_api
  recover_from_connection_close: true

development:
  <<: *defaults
  exchange: published_documents

test:
  <<: *defaults
  exchange: published_documents_test

production:
  hosts:
    <% hosts = ENV['RABBITMQ_HOSTS'] || 'localhost' %>
    <% hosts.split(",").each do |host| %>
    - <%= host %>
    <% end %>
  user: publishing_api
  pass: <%= ENV['RABBITMQ_PASSWORD'] %>
  port: 5672
  vhost: /
  exchange: published_documents
  recover_from_connection_close: true
